services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      # Persist MongoDB data inside the repo under backend/app/data
      - ./app/data/mongo:/data/db
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    environment:
      - LOG_TO_FILES=true
      - LOG_DIR=/var/log/dinnerhopping
    depends_on:
      - mongo
    volumes:
      # expose logs directory on host for persistence and inspection
      - ./logs:/var/log/dinnerhopping

  mongo-init:
    build: .
    command: ["/bin/sh", "-c", "python3 scripts/mongo_init.py --mongo-uri=mongodb://mongo:27017/dinnerhopping"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/dinnerhopping
    depends_on:
      - mongo
    restart: "no"
# Using host bind mounts for persistent data. No named volumes required.