from fastapi import APIRouter, HTTPException, Depends
from .. import db as db_mod
from ..auth import require_admin

router = APIRouter()

@router.post('/match')
async def run_match(_=Depends(require_admin)):
    """Idempotent admin matching: create per-user plans for each event's registrations.

    - Groups registrations in chunks of 6 and assigns three sections per user.
    - Removes existing plan documents for (event_id, user_email) before inserting.
    - Enriches host entries with lat/lon from `users` when available.
    """
    # current_user has been validated by the require_admin dependency

    async for event in db_mod.db.events.find({}):
        regs = []
        async for r in db_mod.db.registrations.find({"event_id": event['_id']}):
            regs.append(r)

        # group into chunks of 6
        chunks = [regs[i:i + 6] for i in range(0, len(regs), 6)]

        for chunk in chunks:
            users = [r['user_email'] for r in chunk]
            if not users:
                continue

            for idx, user_email in enumerate(users):
                # make matching idempotent by removing old plans for this user/event
                await db_mod.db.plans.delete_many({"event_id": event['_id'], "user_email": user_email})

                plan = {"event_id": event['_id'], "user_email": user_email, "sections": []}

                for meal_idx in range(3):
                    host_idx = (idx + meal_idx) % len(users)
                    host_email = users[host_idx]
                    guests = [u for u in users if u != host_email][:4]

                    host_profile = await db_mod.db.users.find_one({"email": host_email})
                    host_lat = host_profile.get('lat') if host_profile else None
                    host_lon = host_profile.get('lon') if host_profile else None

                    section = {
                        'meal': ['Entr\u00e9e', 'Plat Principal', 'Dessert'][meal_idx],
                        'time': '20:00' if meal_idx == 1 else ('18:00' if meal_idx == 0 else '22:00'),
                        'host': {'email': host_email, 'lat': host_lat, 'lon': host_lon},
                        'guests': guests,
                    }

                    plan['sections'].append(section)

                plan['created_at'] = __import__('datetime').datetime.utcnow()
                await db_mod.db.plans.insert_one(plan)

    # NOTE: MATCHES collection (schema: {event_id, groups:[...], status, version, finalized_by, finalized_at, created_at})
    # is not yet generated by this simple matching algorithm. Future implementation
    # could aggregate the above per-event plans into a single matches document.

    return {"status": "matching_completed"}


@router.post('/promote')
async def promote_user(email: str, _=Depends(require_admin)):
    """Grant the 'admin' role to a user identified by email.

    Only callable by existing admins. Returns the updated user doc (safe fields).
    """
    if not email:
        raise HTTPException(status_code=400, detail='email required')
    email = email.lower()
    user = await db_mod.db.users.find_one({'email': email})
    if not user:
        raise HTTPException(status_code=404, detail='User not found')
    roles = user.get('roles') or []
    if 'admin' in roles:
        return {'status': 'already_admin', 'email': email}
    roles = list(set(roles + ['admin']))
    await db_mod.db.users.update_one({'email': email}, {'$set': {'roles': roles, 'updated_at': __import__('datetime').datetime.utcnow()}})
    return {'status': 'promoted', 'email': email}


@router.post('/demote')
async def demote_user(email: str, _=Depends(require_admin)):
    """Revoke the 'admin' role from a user identified by email.

    Protects against demoting the last admin (requires at least one admin to remain).
    """
    if not email:
        raise HTTPException(status_code=400, detail='email required')
    email = email.lower()
    user = await db_mod.db.users.find_one({'email': email})
    if not user:
        raise HTTPException(status_code=404, detail='User not found')
    roles = user.get('roles') or []
    if 'admin' not in roles:
        return {'status': 'not_admin', 'email': email}

    # ensure at least one admin remains
    admin_count = await db_mod.db.users.count_documents({'roles': 'admin'})
    if admin_count <= 1:
        # if this is the last admin, prevent demotion to avoid lockout
        raise HTTPException(status_code=400, detail='Cannot demote the last admin')

    new_roles = [r for r in roles if r != 'admin']
    await db_mod.db.users.update_one({'email': email}, {'$set': {'roles': new_roles, 'updated_at': __import__('datetime').datetime.utcnow()}})
    return {'status': 'demoted', 'email': email}
