services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dinnerhopping
      - MONGO_INITDB_ROOT_PASSWORD=babyschnaps
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: ../backend
    restart: unless-stopped
    env_file:
      - ../backend/app/.env
    environment:
      - LOG_TO_FILES=true
      - LOG_DIR=/var/log/dinnerhopping
    depends_on:
      - mongo
    # On ne publie PAS le port vers l'extérieur, Apache reverse proxynera en local
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ../backend/logs:/var/log/dinnerhopping
volumes:
  mongo-data:
    name: dinnerhopping-mongo-data
