services:
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dinnerhopping
      - MONGO_INITDB_ROOT_PASSWORD=babyschnaps
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: dinnerhopping/backend
    restart: unless-stopped
    env_file:
      - ../backend/app/.env
    environment:
      - LOG_TO_FILES=true
      - LOG_DIR=/var/log/dinnerhopping
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ../backend/logs:/var/log/dinnerhopping
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: dinnerhopping/frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "40332:80"
volumes:
  mongo-data:
    name: dinnerhopping-mongo-data
